### ISSUE TITLE
Is vcmtpRecvv3::Stop() necessary?

### ISSUE THREAD

**Issue by semmerson** [Unidata/vcmtp#26]
I don't see any difference between `vcmtpRecvv3::Stop()` and `vcmtpRecvv3::~vcmtpRecvv3()`. In fact, the destructor calls `Stop()`. The API would be simpler if `Stop()` was eliminated.

**Comment by shawnsschen** [comment]
No. It wouldn't be necessary. Already removed.

**Comment by semmerson** [comment]
Wait. The payload length field isn't needed for the multicast connection, but what about the unicast connection? A TCP connection is just a stream of bytes -- so there's no way to determine the size of a VCMTP packet. If the same VCMTP packets are used in both connections, then the payload length field would seem to be necessary for the unicast connection. Either that or use two different packets: one for multicast and one for unicast.

**Comment by shawnsschen** [comment]
But I thought this issue is discussing the Stop() function. Payload length discussion is in #27

**Comment by semmerson** [comment]
You're right: my previous comment should have gone to #27.

**Comment by semmerson** [comment]
`vcmtpRecvv3::Stop()` is necessary because, otherwise, the destructor will be called twice: once to stop the threads and again when the instance goes out-of-scope -- leading to memory corruption.
