### ISSUE TITLE
potential of dropping all the following packets or NACK implosion

### ISSUE THREAD

**Issue by shawnsschen** [Unidata/vcmtp#28]
VCMTPv3 is implemented under the presumption that packets are all in sequence.
In this case, if a BOP is missing, receiver would request a BOP retransmission. But during this period, following packets are arrived and receiver would find them out of sequence because BOP is not received yet. And the receiver would send a retx request for each single packet (when BOP received, following packets are missed).
This could cause a NACK implosion and all the multicasting packets being dropped.
In the dissertation, the solution is to write the packets into a temporary buffer. I think the solution should be modified to do some metadata check and write them into the prodqueue. What do you think, Steve?

**Comment by semmerson** [comment]
Allocating space for a product in the product-queue requires the size of the product, which isn't known until the BOP message.

**Comment by shawnsschen** [comment]
So the problem is if receiver misses one, it misses all the following packets. Besides using a temporary buffer, do you have any other idea?

**Comment by semmerson** [comment]
The only solution I can think of is to save the data-packets until the relevant BOP arrives and to continue to request re-transmission of missed data-packets -- even one for which no BOP has been received.

**Comment by shawnsschen** [comment]
The discussion leads to a solution that:
1. if BOP is missing. request for BOP retx and drop all of the following pakcets until a BOP is received.
2. if Data is missing. write the following packets directly into the product queue even it's not continuous.
